-- Painel administrativo do Convite Alice
-- Execute este SQL no SQL Editor do Supabase.
-- Não coloque service_role nem qualquer chave secreta no GitHub.

create table if not exists public.event_settings (
  id integer primary key default 1 check (id = 1),
  event_date text not null default '2026-10-25',
  event_time text not null default '15:00',
  event_location text not null default 'Rua Leoberto Leal, 250 — Vorstadt',
  updated_at timestamptz not null default now()
);

insert into public.event_settings (id,event_date,event_time,event_location)
values (1,'2026-10-25','15:00','Rua Leoberto Leal, 250 — Vorstadt')
on conflict (id) do nothing;

create table if not exists public.gift_limits (
  id bigint generated by default as identity primary key,
  category text not null default '',
  name text not null unique,
  limit integer not null default 0 check (limit >= 0),
  updated_at timestamptz not null default now()
);

alter table public.event_settings enable row level security;
alter table public.gift_limits enable row level security;

drop policy if exists "public read event settings" on public.event_settings;
create policy "public read event settings" on public.event_settings for select to anon, authenticated using (true);

drop policy if exists "public read gift limits" on public.gift_limits;
create policy "public read gift limits" on public.gift_limits for select to anon, authenticated using (true);

drop policy if exists "admin manage event settings" on public.event_settings;
create policy "admin manage event settings" on public.event_settings for all to authenticated
using (lower(coalesce(auth.jwt()->>'email','')) = 'tomasandrade1791@gmail.com')
with check (lower(coalesce(auth.jwt()->>'email','')) = 'tomasandrade1791@gmail.com');

drop policy if exists "admin manage gift limits" on public.gift_limits;
create policy "admin manage gift limits" on public.gift_limits for all to authenticated
using (lower(coalesce(auth.jwt()->>'email','')) = 'tomasandrade1791@gmail.com')
with check (lower(coalesce(auth.jwt()->>'email','')) = 'tomasandrade1791@gmail.com');

insert into public.gift_limits (category,name,limit) values
('🍼 Higiene e cuidados','Pacote de fraldas M',0),('🍼 Higiene e cuidados','Pacote de fraldas G',0),('🍼 Higiene e cuidados','Pacote de fraldas XG',0),('🍼 Higiene e cuidados','Lenços umedecidos',0),('🍼 Higiene e cuidados','Sabonete líquido para bebê',0),('🍼 Higiene e cuidados','Creme/pomada para assaduras',0),('🍼 Higiene e cuidados','Kit de higiene para bebê',0),('🍼 Higiene e cuidados','Fraldas de pano',0),
('👕 Roupinhas','Meias',0),('👕 Roupinhas','Casaquinho',0),('👕 Roupinhas','Touquinha',0),('👕 Roupinhas','Babadores',0),
('🛁 Banho','Toalha de banho',0),('🛁 Banho','Toalha com capuz',0),('🛁 Banho','Kit de toalhinhas',0),
('🍼 Alimentação','Escova para mamadeira',0),('🍼 Alimentação','Babador impermeável',0),('🍼 Alimentação','Paninhos de boca',0),
('🛏️ Quarto e sono','Lençol para berço',0),('🛏️ Quarto e sono','Protetor de colchão',0),('🛏️ Quarto e sono','Manta',0),('🛏️ Quarto e sono','Cueiro',0),('🛏️ Quarto e sono','Cobertor apropriado para bebê',0),
('🎀 Presentes especiais','Manta personalizada',0),('🎀 Presentes especiais','Toalha personalizada',0),('🎀 Presentes especiais','Kit de saída da maternidade',0),('🎀 Presentes especiais','Vale-presente de loja infantil',0),
('⭐ Opção livre','Presente escolhido livremente — algo que o convidado considere útil para a Alice ou a mamãe.',0)
on conflict (name) do nothing;

alter table public.rsvps enable row level security;
alter table public.messages enable row level security;

drop policy if exists "public insert rsvps" on public.rsvps;
create policy "public insert rsvps" on public.rsvps for insert to anon, authenticated with check (true);

drop policy if exists "admin read rsvps" on public.rsvps;
create policy "admin read rsvps" on public.rsvps for select to authenticated
using (lower(coalesce(auth.jwt()->>'email','')) = 'tomasandrade1791@gmail.com');

drop policy if exists "public insert messages" on public.messages;
create policy "public insert messages" on public.messages for insert to anon, authenticated with check (true);

drop policy if exists "admin read messages" on public.messages;
create policy "admin read messages" on public.messages for select to authenticated
using (lower(coalesce(auth.jwt()->>'email','')) = 'tomasandrade1791@gmail.com');
