// Cole aqui SOMENTE a URL do projeto e a chave pública (publishable/anon).
// Nunca coloque service_role ou qualquer chave secreta neste arquivo.
window.AliceDB = null;

(function(){
  const OPEN_URL='https://raw.githubusercontent.com/tomasandrade1791-pixel/Ch-de-beb-/main/file_000000007f04820e9ff7fd2ea074c872.png?v=20260921';
  const CLOSED_URL='https://raw.githubusercontent.com/tomasandrade1791-pixel/Ch-de-beb-/main/IMG-20260919-WA0104.jpg?v=20260921';
  function fixAliceStage(){const stage=document.querySelector('.aliceStage');const old=document.querySelector('.aliceArt');if(!stage||stage.dataset.aliceFixed)return;stage.dataset.aliceFixed='1';if(old)old.style.display='none';const sub=stage.querySelector('.sub');if(sub)sub.style.display='none';}
  function initEnvelope(){
    const card=document.getElementById('envCard'),closed=document.getElementById('envClosed'),open=document.getElementById('envOpen'),tap=document.getElementById('tapText');
    if(!card||!closed||!open||!tap||card.dataset.envelopeFixed)return;card.dataset.envelopeFixed='1';closed.src=CLOSED_URL;closed.alt='Cartinha fechada';open.src=OPEN_URL;open.alt='Cartinha aberta';
    const style=document.createElement('style');style.textContent=`#envClosed{display:block!important;opacity:1!important;visibility:visible!important;transform:none!important;z-index:2!important}#envOpen{display:block!important;opacity:0!important;visibility:hidden!important;z-index:1!important;transform:scale(.94)!important;width:min(88vw,620px)!important;height:auto!important;max-height:70vh!important;object-fit:contain!important}#envCard.realOpening #envClosed{display:none!important;opacity:0!important;visibility:hidden!important;pointer-events:none!important}#envCard.realOpening #envOpen{display:block!important;opacity:1!important;visibility:visible!important;z-index:3!important;animation:envelopeOpenIn 1.55s cubic-bezier(.2,.75,.2,1) forwards!important;width:min(88vw,620px)!important;height:auto!important;max-height:70vh!important;object-fit:contain!important}#envCard.realOpening + .tap{display:none!important;opacity:0!important;visibility:hidden!important;pointer-events:none!important}@keyframes envelopeOpenIn{0%{clip-path:inset(100% 0 0 0);opacity:0;transform:translateY(8%) scale(.92)}18%{clip-path:inset(82% 0 0 0);opacity:1;transform:translateY(6%) scale(.94)}45%{clip-path:inset(52% 0 0 0);transform:translateY(3%) scale(.97)}72%{clip-path:inset(24% 0 0 0);transform:translateY(.8%) scale(.99)}100%{clip-path:inset(0 0 0 0);opacity:1;transform:translateY(0) scale(1)}}`;document.head.appendChild(style);
    card.addEventListener('click',function(e){if(card.dataset.realOpened)return;e.preventDefault();e.stopImmediatePropagation();card.dataset.realOpened='1';closed.remove();tap.remove();open.src=OPEN_URL+'&open=1';open.style.setProperty('display','block','important');open.style.setProperty('visibility','visible','important');open.style.setProperty('opacity','1','important');open.style.setProperty('z-index','3','important');card.classList.add('realOpening');setTimeout(function(){if(typeof show==='function')show('rules')},3200)},true);
  }
  function initRulesIntroSplit(){let tries=0;const timer=setInterval(function(){tries++;if(typeof window.renderRule!=='function'||!document.getElementById('rp')){if(tries>100)clearInterval(timer);return}clearInterval(timer);const baseRenderRule=window.renderRule,baseNext=window.next,basePrev=window.prev;let intro=true;window.renderRule=function(){const rp=document.getElementById('rp');if(!rp)return;if(intro)rp.innerHTML='<h1>Combinados para o<br>⭐ nosso dia ⭐</h1><p class="intro"><strong>Queridos amigos e familiares,</strong><br>Para que possamos aproveitar esse momento tão especial com tranquilidade, carinho e alegria, preparamos alguns pequenos combinados.<br><br>Agradecemos desde já a compreensão e o carinho de todos com nossa família e, principalmente, com a nossa pequena. 💙🍼</p><div class="nav"><button class="btn" disabled>‹ VOLTAR</button><span class="counter">INTRODUÇÃO</span><button class="btn" onclick="next()">COMEÇAR ›</button></div>';else baseRenderRule()};window.next=function(){if(intro){intro=false;ri=0;window.renderRule()}else baseNext()};window.prev=function(){if(!intro&&ri===0){intro=true;window.renderRule()}else if(!intro)basePrev()};intro=true;ri=0;window.renderRule()},100)}
  function init(){fixAliceStage();initEnvelope();initRulesIntroSplit()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();